name: soho_app
description: Soho

version: 1.0.0+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: 0.5.7+2
  path_provider: 1.5.1
  path: 1.6.4
  flutter_facebook_auth: ^0.2.2+1
  google_sign_in: ^4.0.6
  firebase_auth: ^0.11.1+12
  flutter_secure_storage: ^3.2.1+1
  get_it: ^1.0.3+2
  scoped_model: ^1.0.1
  fluro: ^1.5.1
  after_layout: ^1.0.7+2
  http: ^0.12.0+2
  firebase_database: ^3.0.5
  carousel_slider: ^1.3.0
  firebase_storage: ^3.0.6
  stripe_payment: ^1.0.6
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.4+5
  circular_check_box: ^1.0.1
  material_segmented_control: ^2.0.7
  uuid: 2.0.4
  cupertino_icons: ^0.1.2
  intl: 0.16.0
  qr_flutter: ^3.1.0
  image_picker: ^0.6.2+3
  image_cropper: ^1.1.1
  flutter_image_compress: ^0.6.3
  flutter_masked_text: ^0.8.0
  firebase_messaging: ^5.1.6
  barcode_scan: ^1.0.0
  flutter_share_file: ^1.1.4+1
  flutter_launcher_icons: ^0.7.4
  mailer: ^3.0.4
  fluttertoast: ^3.1.3
  url_launcher: ^5.4.2
  geolocator: ^5.3.1
  connectivity: ^0.4.8+2
  email_validator: ^1.0.0

flutter_icons:
  image_path: 'assets/launcher/icon.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/splash/
    - assets/home/
    - assets/category_detail/
    - assets/menu/
    - assets/auth/
    - assets/purchases/
    - assets/icons/
    - assets/payments/

  fonts:
    - family: LatoBlack
      fonts:
        - asset: fonts/Lato-Black.ttf
    - family: LatoBlackItalic
      fonts:
        - asset: fonts/Lato-BlackItalic.ttf
    - family: LatoBold
      fonts:
        - asset: fonts/Lato-Bold.ttf
    - family: LatoBoldItalic
      fonts:
        - asset: fonts/Lato-BoldItalic.ttf
    - family: LatoItalic
      fonts:
        - asset: fonts/Lato-Italic.ttf
    - family: LatoLight
      fonts:
        - asset: fonts/Lato-Light.ttf
    - family: LatoLightItalic
      fonts:
        - asset: fonts/Lato-LightItalic.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: LatoThin
      fonts:
        - asset: fonts/Lato-Thin.ttf
    - family: LatoThinItalic
      fonts:
        - asset: fonts/Lato-ThinItalic.ttf
